name: GitHub Release

concurrency: deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-me:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Run ReleaseMe
        id: release
        uses: dev-build-deploy/release-me@v0
        with:
          token: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
          prefix: v                    # OPTIONAL; prefixes the version with v (e.g. v1.0.0)
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: ${{ steps.release.outputs.created }}
        run: echo ${{ fromJSON(steps.release.outputs.release).tag_name }}

      - name: Split package
        uses: "claudiodekker/splitsh-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
        with:
          prefix: "library"
          remote: "https://github.com/kduma-archive/test-ci-git-split-library.git"
          reference: "${{ github.ref_name }}"
          as_tag: "${{ startsWith(github.ref, 'refs/tags/') }}"
