name: 'Split monorepo'

on:
  push:
    branches:
      - main
      - develop
      - '*.x'
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Split package
        uses: "claudiodekker/splitsh-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.MONOREPO_SPLITTER_PERSONAL_ACCESS_TOKEN }}
        with:
          prefix: "library"
          remote: "https://github.com/kduma-archive/test-ci-git-split-library.git"
          reference: "${{ github.ref_name }}"
          as_tag: "${{ startsWith(github.ref, 'refs/tags/') }}"
